# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0c1ed08de5f8f2ea0af6ab08215aeb7695ab1f6d915e44e908a693f7ab17a3a5b9ddd6eabbddc7d71bf5a53c53c56543a24b28572da90156131ba8deba17050f

test:
  secret_key_base: 48024a1a837203996da2a5305b6879c63826b8a80235e69feceac1da39faf41b6d2136befbb1f0382a2e8719a6351081543e8ba0b4c674fcfeee44c5cda1261f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
